const musicTables = [
    "album_currentlyListening",
    "album_allgenres",
    "album_ambientvaporwave",
    "album_bedroomAOR",
    "artist_classicalComposer",
    "album_createdbyrejection",
    "album_dreamytranscendent",
    "album_emo",
    "album_greatscene",
    "album_hopelessrecords",
    "album_indiepop",
    "album_jazz",
    "album_magicsheet",
    "album_moenieandkitchie",
    "album_popalbums",
    "album_poppunk",
    "album_poppunkuplifting",
    "album_risecore",
    "album_rymrecs",
    "album_rymsuggestions",
    "album_soothingambient",
    "album_soundsofspotify",
    "album_telepath",
    "album_topalbums",
    "artist_topartists",
    "album_unsungdreampop",
    "album_vaporwave",
    "album_vaporwavesources",
    "album_vinyls",
    "album_waterloggedEars",
    "artist_underground",
    "album_4Point5",
];

const filmTables = [
    "film_ebert",
    "film_imdb250",
    "filmrecs",
    "film_towatch",
    "film_visualhypnagogia",
    "film_rymtop1500",
    "film_criterion",
    "film_noir1000",
    "film_stremiolibrary",
    "film_tspdt2500",
    "film_70s",
    "film_80s",
    "film_90s",
    "film_addtostremio",
];

const showTables = ["shows", "anime_classic", "anime_other", "shows_top50"];

const bookTables = [
    "book_toread",
    "book_4chan",
    "book_1001",
    "book_manga",
    "book_anthologies",
];

const allTables = [
    "album_currentlyListening",
    "album_2011vwave",
    "album_4Point5",
    "album_allgenres",
    "album_ambientvaporwave",
    "album_bedroomAOR",
    "artist_classicalComposer",
    "album_createdbyrejection",
    "album_dreamytranscendent",
    "album_emo",
    "album_greatscene",
    "album_hopelessrecords",
    "album_indiepop",
    "album_magicsheet",
    "album_mallsoft",
    "album_moenieandkitchie",
    "album_popalbums",
    "album_poppunk",
    "album_poppunkuplifting",
    "album_risecore",
    "album_rymrecs",
    "album_rymsuggestions",
    "album_soundsofspotify",
    "album_tolisten",
    "album_telepath",
    "album_soothingambient",
    "artist_topartists",
    "album_unsungdreampop",
    "album_vaporwave",
    "album_vinyls",
    "album_waterloggedEars",
    "film_ebert",
    "film_imdb250",
    "filmrecs",
    "film_towatch",
    "film_visualhypnagogia",
    "film_rymtop1500",
    "film_italian",
    "film_criterion",
    "film_noir1000",
    "film_stremiolibrary",
    "film_tspdt2500",
    "film_70s",
    "film_80s",
    "film_90s",
    "shows",
    "anime_classic",
    "anime_other",
    "shows_top50",
    "book_toread",
    "book_manga",
    "book_1001",
    "book_anthologies",
];

const bookAnthologies = [
    "Stories of Your Life and Others",
    "The Stars My Destination",
    "Greatest Short Stories Volume 4",
    "Great American Short Stories",
    "The Treasury of English Short Stories",
    "Mark Twain Short Stories",
    "Classic Short Stories",
    "Everythings Eventual",
    "We Can Remember It For You Wholesale",
    "LLA1",
    "Interfaces",
    "Year's Best Science Fiction",
    "LLA2",
    "Esquire",
    "LLA3",
    "LLA4",
    "LLA6",
    "Twentieth Century Drama",
    "Mystery And Suspense",
    "Ten Of The Best",
    "Pulp Fiction",
    "Hitchcock",
    "Ursula K Le Guin",
    "Harlan Ellison",
];

const musicTablesMap = {
    album_currentlyListening: "Currently listening",
    album_allgenres: "Favorite genres",
    album_ambientvaporwave: "Ambient vaporwave",
    album_bedroomAOR: "RYM profile: bedroomAOR",
    artist_classicalComposer: "Classical composers",
    album_createdbyrejection: "RYM profile: createdbyrejection",
    album_dreampop: "Top dream pop albums",
    album_dreamytranscendent: "RYM tags: dreamy/transcendent",
    album_emo: "Top emo albums",
    album_greatscene: "Great scene chronology",
    album_hopelessrecords: "Record label: Hopeless",
    album_indiepop: "Top indie pop albums",
    album_jazz: "Top jazz albums",
    album_magicsheet: "Magic sheet",
    album_moenieandkitchie: "Albums like Moenie and Kitchie",
    album_popalbums: "Top pop albums",
    album_poppunk: "Top pop punk albums",
    album_poppunkuplifting: "Uplifting pop punk albums",
    album_risecore: "Record label: Rise",
    album_rymrecs: "RYM recommendations",
    album_rymsuggestions: "RYM suggestions",
    album_soothingambient: "RYM tags: soothing/ambient",
    album_soundsofspotify: "Sounds of Spotify",
    album_telepath: "Telepath",
    album_topalbums: "Top albums of x year",
    artist_topartists: "My top artists",
    album_unsungdreampop: "Unsung dream pop",
    album_vaporwave: "Top vaporwave albums",
    album_vaporwavesources: "Vaporwave sources",
    album_vinyls: "My vinyls",
    album_waterloggedEars: "Waterlogged Ears playlist",
    artist_underground: "Top underground rap artists",
    album_4Point5: "Albums I gave a 4.5",
};

const filmTablesMap = {
    film_ebert: "Roger Ebert's top films",
    film_imdb250: "IMDb Top 250",
    filmrecs: "RYM Film Recs",
    film_towatch: "Want to watch",
    film_visualhypnagogia: "Visual Hypnagogia list",
    film_rymtop1500: "RYM Top 1500",
    film_criterion: "Criterion list",
    film_noir1000: "Top 1000 film noir",
    film_stremiolibrary: "My stremio library",
    film_tspdt2500: "TSPDT Top 2500",
    film_70s: "Top 70s films",
    film_80s: "Top 80s films",
    film_90s: "Top 90s films",
    film_addtostremio: "Add to stremio",
};

const showTablesMap = {
    shows: "All shows",
    anime_classic: "Classic anime",
    anime_other: "Other anime",
    shows_top50: "IMDb Top 50",
};

const bookTablesMap = {
    book_toread: "My shelf",
    book_4chan: "4chan Top 100",
    book_1001: "Goodreads Top 1001",
    book_manga: "Top manga",
    book_anthologies: "My anthologies",
};

export {
    musicTables,
    musicTablesMap,
    filmTables,
    filmTablesMap,
    showTables,
    showTablesMap,
    bookTables,
    bookTablesMap,
    allTables,
    bookAnthologies,
};
