const musicTables = [
    "album_currentlyListening",
    "album_2000smidwest",
    "album_2011vwave",
    "album_4Point5",
    "album_80slushpop",
    "album_80snocturnalpop",
    "album_abstractsummer",
    "album_allgenres",
    "album_alternativer_b",
    "album_ambientvaporwave",
    "album_baggy",
    "album_bedroomAOR",
    "album_citydowntempo",
    "album_cityhouse",
    "artist_classicalComposer",
    "album_contemporaryr_b",
    "album_createdbyrejection",
    "album_crabcore",
    "album_dreampop",
    "album_dreamygarage",
    "album_dreamyhiphop",
    "album_dreamysophisti",
    "album_dreamysynthpop",
    "album_dreamytranscendent",
    "album_easycore",
    "album_easylistening",
    "album_etherealjangle",
    "album_emo",
    "album_emogaze",
    "album_emopop",
    "album_etherealslowcore",
    "album_fantano",
    "album_folk",
    "album_funk",
    "album_glitch",
    "album_greatscene",
    "album_hopelessrecords",
    "album_hypnagogicpop",
    "album_hypnoticsynthpop",
    "album_indiefolk",
    "album_indiepop",
    "album_indiesleaze",
    "album_janglefemale",
    "album_jazz",
    "album_kpop",
    "album_late2000sindie",
    "album_magicsheet",
    "album_mallsoft",
    "album_mathpop",
    "album_mathpostemo",
    "album_meditativepostrock",
    "album_metalcore",
    "album_midwest",
    "album_moenieandkitchie",
    "album_neonpoppunk",
    "album_neosoul",
    "album_orangemilkrecords",
    "album_pluggnb",
    "album_popalbums",
    "album_poppunk",
    "album_poppunkuplifting",
    "album_posthardcore",
    "album_progsoul",
    "album_risecore",
    "album_rymrecs",
    "album_rymsuggestions",
    "album_selectedethereal",
    "album_shoegaze",
    "album_shoegazefemale",
    "album_shoegazerelics",
    "album_shoegazeuplifting",
    "album_smoothjazz",
    "album_smoothsoul",
    "album_soul",
    "album_soundsofspotify",
    "album_telepath",
    "album_tolisten",
    "album_topalbums",
    "album_topartistdiscogs",
    "album_tweepunk",
    "album_soothingambient",
    "artist_topartists",
    "album_vaporwave",
    "album_vaporwavesources",
    "album_unsungdreampop",
    "album_utopianscholastic",
    "album_urban",
    "album_vinyls",
    "album_warmlofi",
    "album_waterloggedEars",
    "artist_underground",
];

const filmTables = [
    "film_70s",
    "film_80s",
    "film_90s",
    "film_addtostremio",
    "film_cahiers",
    "film_criterion",
    "film_cry",
    "film_cult",
    "film_ebert",
    "film_imdb250",
    "film_international",
    "film_noir1000",
    "film_rymtop1500",
    "film_stremiolibrary",
    "film_top150fromhappiness",
    "film_towatch",
    "film_tspdt2500",
    "film_visualhypnagogia",
    "film_weird",
    "filmrecs",
];

const showTables = [
    "shows",
    "anime_classic",
    "anime_other",
    "shows_top50",
    "shows_stremio",
];

const bookTables = [
    "book_1001",
    "book_4chan",
    "book_anthologies",
    "book_manga",
    "book_toread",
    "book_penguinmodern",
    "book_penguinblack",
];

const allTables = [
    "album_currentlyListening",
    "album_2000smidwest",
    "album_2011vwave",
    "album_4Point5",
    "album_80slushpop",
    "album_80snocturnalpop",
    "album_abstractsummer",
    "album_allgenres",
    "album_alternativer_b",
    "album_ambientvaporwave",
    "album_baggy",
    "album_bedroomAOR",
    "album_citydowntempo",
    "album_cityhouse",
    "artist_classicalComposer",
    "album_contemporaryr_b",
    "album_createdbyrejection",
    "album_crabcore",
    "album_dreampop",
    "album_dreamygarage",
    "album_dreamyhiphop",
    "album_dreamysophisti",
    "album_dreamysynthpop",
    "album_dreamytranscendent",
    "album_easycore",
    "album_easylistening",
    "album_etherealjangle",
    "album_emo",
    "album_emogaze",
    "album_emopop",
    "album_etherealslowcore",
    "album_faketable",
    "album_fantano",
    "album_folk",
    "album_funk",
    "album_glitch",
    "album_greatscene",
    "album_hopelessrecords",
    "album_hypnagogicpop",
    "album_hypnoticsynthpop",
    "album_indiefolk",
    "album_indiepop",
    "album_indiesleaze",
    "album_janglefemale",
    "album_jazz",
    "album_kpop",
    "album_late2000sindie",
    "album_magicsheet",
    "album_mallsoft",
    "album_mathpop",
    "album_mathpostemo",
    "album_meditativepostrock",
    "album_metalcore",
    "album_midwest",
    "album_moenieandkitchie",
    "album_neonpoppunk",
    "album_neosoul",
    "album_orangemilkrecords",
    "album_pluggnb",
    "album_popalbums",
    "album_poppunk",
    "album_poppunkuplifting",
    "album_posthardcore",
    "album_progsoul",
    "album_risecore",
    "album_rymrecs",
    "album_rymsuggestions",
    "album_selectedethereal",
    "album_shoegaze",
    "album_shoegazefemale",
    "album_shoegazerelics",
    "album_shoegazeuplifting",
    "album_smoothjazz",
    "album_smoothsoul",
    "album_soul",
    "album_soundsofspotify",
    "album_telepath",
    "album_tolisten",
    "album_topalbums",
    "album_topartistdiscogs",
    "album_tweepunk",
    "album_soothingambient",
    "artist_topartists",
    "album_vaporwave",
    "album_vaporwavesources",
    "album_unsungdreampop",
    "album_utopianscholastic",
    "album_urban",
    "album_vinyls",
    "album_warmlofi",
    "album_waterloggedEars",
    "artist_underground",
    "film_ebert",
    "film_imdb250",
    "filmrecs",
    "film_towatch",
    "film_top150fromhappiness",
    "film_cry",
    "film_visualhypnagogia",
    "film_rymtop1500",
    "film_criterion",
    "film_italian",
    "film_noir1000",
    "film_stremiolibrary",
    "film_tspdt2500",
    "film_70s",
    "film_80s",
    "film_90s",
    "film_cult",
    "film_weird",
    "film_cahiers",
    "shows",
    "anime_classic",
    "anime_other",
    "shows_top50",
    "shows_stremio",
    "book_toread",
    "book_manga",
    "book_1001",
    "book_penguinmodern",
    "book_penguinblack",
];

const bookAnthologies = [
    "Classic Short Stories",
    "Esquire",
    "Everythings Eventual",
    "Great American Short Stories",
    "Greatest Short Stories Volume 4",
    "Harlan Ellison",
    "Hitchcock",
    "Interfaces",
    "LLA1",
    "LLA2",
    "LLA3",
    "LLA4",
    "LLA6",
    "Mark Twain Short Stories",
    "Mystery And Suspense",
    "Pulp Fiction",
    "Stories of Your Life and Others",
    "Ten Of The Best",
    "The Stars My Destination",
    "The Treasury of English Short Stories",
    "Twentieth Century Drama",
    "Ursula K Le Guin",
    "We Can Remember It For You Wholesale",
    "Year's Best Science Fiction",
];

const musicTablesMap = {
    album_currentlyListening: "Currently listening",
    album_allgenres: "Favorite genres",
    album_ambientvaporwave: "Ambient vaporwave",
    album_bedroomAOR: "RYM profile: bedroomAOR",
    artist_classicalComposer: "Classical composers",
    album_createdbyrejection: "RYM profile: createdbyrejection",
    album_crabcore: "Crabcore and crabcore adjacent",
    album_dreampop: "Top dream pop albums",
    album_dreamytranscendent: "RYM tags: dreamy/transcendent",
    album_emo: "Top emo albums",
    album_folk: "Top folk albums",
    album_greatscene: "Great scene chronology",
    album_hopelessrecords: "Record label: Hopeless",
    album_indiefolk: "Top indie folk albums",
    album_indiepop: "Top indie pop albums",
    album_jazz: "Top jazz albums",
    album_magicsheet: "Magic sheet",
    album_moenieandkitchie: "Albums like Moenie and Kitchie",
    album_orangemilkrecords: "Record label: OMR",
    album_popalbums: "Top pop albums",
    album_poppunk: "Top pop punk albums",
    album_poppunkuplifting: "Uplifting pop punk albums",
    album_posthardcore: "Top post-hardcore emo albums",
    album_risecore: "Record label: Rise",
    album_rymrecs: "RYM recommendations",
    album_rymsuggestions: "RYM suggestions",
    album_soothingambient: "RYM tags: soothing/ambient",
    album_soundsofspotify: "Sounds of Spotify",
    album_telepath: "Telepath",
    album_topalbums: "Top albums of x year",
    artist_topartists: "My top artists",
    album_tweepunk: "Top twee punk albums",
    album_unsungdreampop: "Unsung dream pop",
    album_vaporwave: "Top vaporwave albums",
    album_vaporwavesources: "Vaporwave sources",
    album_vinyls: "My vinyls",
    album_waterloggedEars: "Waterlogged Ears playlist",
    artist_underground: "Top underground rap artists",
    album_4Point5: "Albums I gave a 4.5",
    album_easycore: "Top easycore albums",
    album_fantano: "Top Fantano albums",
    album_neosoul: "Top neosoul albums",
    album_pluggnb: "Top pluggnb albums",
    album_alternativer_b: "Top alternative r&b albums",
    album_contemporaryr_b: "Top contemporary r&b albums",
    album_utopianscholastic: "Utopian Scholastic playlist",
    album_easylistening: "Easy listening playlist",
    album_urban: "Urban albums",
    album_dreamysophisti: "Dreamy sophisti-pop",
    album_hypnoticsynthpop: "Hypnotic synth pop",
    album_etherealslowcore: "Ethereal slowcore",
    album_emopop: "Emo pop",
    album_dreamygarage: "Dreamy garage",
    album_2000smidwest: "2000s Midwest Emo",
    album_dreamyhiphop: "Dreamy hip-hop",
    album_kpop: "Kpop albums",
    album_smoothjazz: "Top smooth jazz albums",
    album_glitch: "Dreamy glitch albums",
    album_cityhouse: "House to explore cities",
    album_etherealjangle: "Ethereal jangle pop",
    album_emogaze: "Emogaze",
    album_selectedethereal: "Selected ethereal works",
    album_80snocturnalpop: "80s nocturnal pop",
    album_meditativepostrock: "Meditative post rock",
    album_80slushpop: "80s lush pop",
    album_citydowntempo: "Downtempo to explore cities",
    album_warmlofi: "Warm lofi treasures",
    album_shoegaze: "Top 100 shoegaze on RYM",
    album_shoegazeuplifting: "Uplifting shoegaze",
    album_shoegazerelics: "Shoegaze relics",
    album_shoegazefemale: "Female fronted shoegaze",
    album_janglefemale: "Female fronted jangle pop",
    album_baggy: "Top 20 baggy on RYM",
    album_midwest: "Twinkly midwest artists",
    album_mathpostemo: "Math/post rock, post hardcore, emo",
    album_mathpop: "Top math pop albums",
    album_metalcore: "Top metalcore albums",
    album_neonpoppunk: "Neon pop punk",
    album_abstractsummer: "Abstract summer",
    album_late2000sindie: "Late 2000s indie",
    album_hypnagogicpop: "Hypnagogic pop",
    album_indiesleaze: "Indie sleaze",
    album_tolisten: "Albums to listen to",
    album_topartistdiscogs: "Unlistened albums from top artists",
    album_smoothsoul: "Top smooth soul albums",
    album_soul: "Top soul albums",
    album_funk: "Top funk albums",
    album_progsoul: "Top prog soul albums"
};

const filmTablesMap = {
    film_ebert: "Roger Ebert's top films",
    film_imdb250: "IMDb Top 250",
    filmrecs: "RYM Film Recs",
    film_towatch: "Want to watch",
    film_visualhypnagogia: "Visual Hypnagogia list",
    film_rymtop1500: "RYM Top 1500",
    film_criterion: "Criterion list",
    film_noir1000: "Top 1000 film noir",
    film_stremiolibrary: "My stremio library",
    film_tspdt2500: "TSPDT Top 2500",
    film_70s: "Top 70s films",
    film_80s: "Top 80s films",
    film_90s: "Top 90s films",
    film_addtostremio: "Add to stremio",
    film_international: "International films",
    film_cult: "Cult classics",
    film_weird: "366 Weird Films",
    film_cahiers: "Cahiers du Cinema Annual Top 10",
    film_cry: "Crying movies JamesLovesWeirdness",
    film_top150fromhappiness: "JamesLovesWeirdness favs",
};

const showTablesMap = {
    shows: "All shows",
    anime_classic: "Classic anime",
    anime_other: "Other anime",
    shows_top50: "IMDb Top 50",
    shows_stremio: "Shows on Stremio",
};

const bookTablesMap = {
    book_toread: "My shelf",
    book_4chan: "4chan Top 100",
    book_1001: "Goodreads Top 1001",
    book_manga: "Top manga",
    book_anthologies: "My anthologies",
    book_penguinblack: "Little black classics",
    book_penguinmodern: "Little modern classics",
};

export {
    musicTables,
    musicTablesMap,
    filmTables,
    filmTablesMap,
    showTables,
    showTablesMap,
    bookTables,
    bookTablesMap,
    allTables,
    bookAnthologies,
};
