const musicTables = [
    "album_currentlyListening",
    "album_allgenres",
    "album_ambientvaporwave",
    "album_bedroomAOR",
    "artist_classicalComposer",
    "album_createdbyrejection",
    "album_dreampop",
    "album_dreamytranscendent",
    "album_emo",
    "album_greatscene",
    "album_hopelessrecords",
    "album_indiepop",
    "album_jazz",
    "album_magicsheet",
    "album_moenieandkitchie",
    "album_popalbums",
    "album_risecore",
    "album_rymrecs",
    "album_rymsuggestions",
    "album_soothingambient",
    "album_soundsofspotify",
    "album_telepath",
    "album_topalbums",
    "artist_topartists",
    "album_vaporwave",
    "album_vaporwavesources",
    "album_vinyls",
    "album_waterloggedEars",
    "artist_underground",
    "album_4Point5",
];

const filmTables = [
    "film_ebert",
    "film_imdb250",
    "filmrecs",
    "film_towatch",
    "film_visualhypnagogia",
    "film_rymtop1500",
    "film_criterion",
    "film_noir1000",
    "film_tspdt2500",
    "film_70s",
    "film_80s",
    "film_90s",
];

const showTables = ["shows", "anime_classic", "anime_other", "shows_top50"];

const bookTables = ["book_toread", "book_4chan", "book_1001", "book_manga"];

const allTables = [
    "album_currentlyListening",
    "album_2011vwave",
    "album_4Point5",
    "album_allgenres",
    "album_ambientvaporwave",
    "album_bedroomAOR",
    "artist_classicalComposer",
    "album_createdbyrejection",
    "album_dreamytranscendent",
    "album_emo",
    "album_greatscene",
    "album_hopelessrecords",
    "album_indiepop",
    "album_magicsheet",
    "album_mallsoft",
    "album_moenieandkitchie",
    "album_popalbums",
    "album_risecore",
    "album_rymrecs",
    "album_rymsuggestions",
    "album_soundsofspotify",
    "album_tolisten",
    "album_telepath",
    "album_soothingambient",
    "artist_topartists",
    "album_vaporwave",
    "album_vinyls",
    "album_waterloggedEars",
    "film_ebert",
    "film_imdb250",
    "filmrecs",
    "film_towatch",
    "film_visualhypnagogia",
    "film_rymtop1500",
    "film_criterion",
    "film_noir1000",
    "film_tspdt2500",
    "film_70s",
    "film_80s",
    "film_90s",
    "shows",
    "anime_classic",
    "anime_other",
    "shows_top50",
    "book_toread",
    "book_manga",
    "book_1001",
];

const bookAnthologies = [
    "ted chiang",
    "the stars my destination",
    "greatest short stories volume 4",
    "great american short stories",
    "the treasury of english short stories",
    "mark twain short stories",
    "classic short stories",
    "everythings eventual",
    "we can remember it for you wholesale",
    "LLA1",
    "interfaces",
    "years best science fiction",
    "LLA2",
    "esquire",
    "LLA3",
    "LLA4",
    "LLA6",
    "twentieth century drama",
    "mystery and suspense",
    "ten of the best",
    "pulp fiction",
    "hitchcock",
    "ursula k le guin",
    "harlan ellison",
];

export {
    musicTables,
    filmTables,
    showTables,
    bookTables,
    allTables,
    bookAnthologies,
};
