const musicTables = [
    "album_currentlyListening",
    "album_2000smidwest",
    "album_2011vwave",
    "album_4Point5",
    "album_80slushpop",
    "album_80snocturnalpop",
    "album_allgenres",
    "album_alternativer_b",
    "album_ambientvaporwave",
    "album_baggy",
    "album_bedroomAOR",
    "album_citydowntempo",
    "album_cityhouse",
    "artist_classicalComposer",
    "album_contemporaryr_b",
    "album_createdbyrejection",
    "album_crabcore",
    "album_dreampop",
    "album_dreamygarage",
    "album_dreamyhiphop",
    "album_dreamysophisti",
    "album_dreamysynthpop",
    "album_dreamytranscendent",
    "album_easycore",
    "album_easylistening",
    "album_etherealjangle",
    "album_emo",
    "album_emogaze",
    "album_emopop",
    "album_etherealslowcore",
    "album_fantano",
    "album_folk",
    "album_glitch",
    "album_greatscene",
    "album_hopelessrecords",
    "album_hypnoticsynthpop",
    "album_indiefolk",
    "album_indiepop",
    "album_janglefemale",
    "album_jazz",
    "album_kpop",
    "album_magicsheet",
    "album_mallsoft",
    "album_mathpostemo",
    "album_meditativepostrock",
    "album_midwest",
    "album_moenieandkitchie",
    "album_neosoul",
    "album_orangemilkrecords",
    "album_pluggnb",
    "album_popalbums",
    "album_poppunk",
    "album_poppunkuplifting",
    "album_posthardcore",
    "album_risecore",
    "album_rymrecs",
    "album_rymsuggestions",
    "album_selectedethereal",
    "album_shoegaze",
    "album_shoegazefemale",
    "album_shoegazerelics",
    "album_shoegazeuplifting",
    "album_smoothjazz",
    "album_soundsofspotify",
    "album_telepath",
    "album_tolisten",
    "album_topalbums",
    "album_tweepunk",
    "album_soothingambient",
    "artist_topartists",
    "album_vaporwave",
    "album_vaporwavesources",
    "album_unsungdreampop",
    "album_utopianscholastic",
    "album_urban",
    "album_vinyls",
    "album_warmlofi",
    "album_waterloggedEars",
    "artist_underground",
];

const filmTables = [
    "film_ebert",
    "film_imdb250",
    "filmrecs",
    "film_towatch",
    "film_visualhypnagogia",
    "film_rymtop1500",
    "film_criterion",
    "film_noir1000",
    "film_stremiolibrary",
    "film_tspdt2500",
    "film_70s",
    "film_80s",
    "film_90s",
    "film_international",
    "film_cult",
    "film_weird",
    "film_cahiers",
    "film_cry",
    "film_top150fromhappiness",
];

const showTables = [
    "shows",
    "anime_classic",
    "anime_other",
    "shows_top50",
    "shows_stremio",
];

const bookTables = [
    "book_toread",
    "book_4chan",
    "book_1001",
    "book_manga",
    "book_anthologies",
    "book_penguinmodern",
    "book_penguinblack",
];

const allTables = [
    "album_currentlyListening",
    "album_2000smidwest",
    "album_2011vwave",
    "album_4Point5",
    "album_80slushpop",
    "album_80snocturnalpop",
    "album_allgenres",
    "album_alternativer_b",
    "album_ambientvaporwave",
    "album_baggy",
    "album_bedroomAOR",
    "album_citydowntempo",
    "album_cityhouse",
    "artist_classicalComposer",
    "album_contemporaryr_b",
    "album_createdbyrejection",
    "album_crabcore",
    "album_dreampop",
    "album_dreamygarage",
    "album_dreamyhiphop",
    "album_dreamysophisti",
    "album_dreamysynthpop",
    "album_dreamytranscendent",
    "album_easycore",
    "album_easylistening",
    "album_etherealjangle",
    "album_emo",
    "album_emogaze",
    "album_emopop",
    "album_etherealslowcore",
    "album_fantano",
    "album_folk",
    "album_glitch",
    "album_greatscene",
    "album_hopelessrecords",
    "album_hypnoticsynthpop",
    "album_indiefolk",
    "album_indiepop",
    "album_janglefemale",
    "album_jazz",
    "album_kpop",
    "album_magicsheet",
    "album_mallsoft",
    "album_mathpostemo",
    "album_meditativepostrock",
    "album_midwest",
    "album_moenieandkitchie",
    "album_neosoul",
    "album_orangemilkrecords",
    "album_pluggnb",
    "album_popalbums",
    "album_poppunk",
    "album_poppunkuplifting",
    "album_posthardcore",
    "album_risecore",
    "album_rymrecs",
    "album_rymsuggestions",
    "album_selectedethereal",
    "album_shoegaze",
    "album_shoegazefemale",
    "album_shoegazerelics",
    "album_shoegazeuplifting",
    "album_smoothjazz",
    "album_soundsofspotify",
    "album_telepath",
    "album_tolisten",
    "album_topalbums",
    "album_tweepunk",
    "album_soothingambient",
    "artist_topartists",
    "album_vaporwave",
    "album_vaporwavesources",
    "album_unsungdreampop",
    "album_utopianscholastic",
    "album_urban",
    "album_vinyls",
    "album_warmlofi",
    "album_waterloggedEars",
    "artist_underground",
    "film_ebert",
    "film_imdb250",
    "filmrecs",
    "film_towatch",
    "film_visualhypnagogia",
    "film_rymtop1500",
    "film_criterion",
    "film_italian",
    "film_noir1000",
    "film_stremiolibrary",
    "film_tspdt2500",
    "film_70s",
    "film_80s",
    "film_90s",
    "film_cult",
    "film_weird",
    "film_cahiers",
    "film_cry",
    "film_top150fromhappiness",
    "shows",
    "anime_classic",
    "anime_other",
    "shows_top50",
    "shows_stremio",
    "book_toread",
    "book_manga",
    "book_1001",
    "book_penguinmodern",
    "book_penguinblack",
];

const bookAnthologies = [
    "ted chiang",
    "the stars my destination",
    "greatest short stories volume 4",
    "great american short stories",
    "the treasury of english short stories",
    "mark twain short stories",
    "classic short stories",
    "everythings eventual",
    "we can remember it for you wholesale",
    "LLA1",
    "interfaces",
    "years best science fiction",
    "LLA2",
    "esquire",
    "LLA3",
    "LLA4",
    "LLA6",
    "twentieth century drama",
    "mystery and suspense",
    "ten of the best",
    "pulp fiction",
    "hitchcock",
    "ursula k le guin",
    "harlan ellison",
];

export {
    musicTables,
    filmTables,
    showTables,
    bookTables,
    allTables,
    bookAnthologies,
};
